name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Check gofmt
      run: |
        fmt_result=$(gofmt -l .)
        if [ -n "$fmt_result" ]; then
          echo "The following files need to be formatted:"
          echo "$fmt_result"
          exit 1
        fi

  build:
    name: Build EC Daemon
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Set up Go environment variables
      run: |
        echo "export PATH=\$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV

    - name: Install dependencies
      run: go mod download

    - name: Install buf
      run: |
        wget https://github.com/bufbuild/buf/releases/download/v1.32.0/buf-Linux-x86_64 -O buf
        chmod +x buf
        sudo mv buf /usr/local/bin/buf

    - name: Install gRPC and protobuf plugins
      run: |
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Build the project
      run: make build

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: make test
